name: Store latest deploy metadata
on:
# schedule:
#   - cron: '*/5 * * * *'
  workflow_dispatch:
env:
  INFLUX_API_TOKEN: ${{ secrets.INFLUX_API_TOKEN }}
  INFLUX_URL: ${{ secrets.INFLUX_URL }}
  INFLUX_BUCKET_NAME: ${{ secrets.INFLUX_BUCKET_NAME }}
  INFLUX_ORGANISATION_NAME: ${{ secrets.INFLUX_ORGANISATION_NAME }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  RPR_STAGING_BASIC_AUTH_USERNAME: ${{ secrets.RPR_STAGING_BASIC_AUTH_USERNAME }}
  RPR_STAGING_BASIC_AUTH_PASSWORD: ${{ secrets.RPR_STAGING_BASIC_AUTH_PASSWORD }}
jobs:
  default-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle install
      - run: ruby scripts/analyse_latest_release.rb
