name: Store latest deploy metadata
on:
# schedule:
#   - cron: '*/5 * * * *'
  workflow_dispatch:
env:
  INFLUX_API_TOKEN: ${{secrets.INFLUX_API_TOKEN}}
  INFLUX_URL: ${{ secrets.INFLUX_URL }}
  INFLUX_BUCKET_NAME: ${{ secrets.INFLUX_BUCKET_NAME }}
  INFLUX_ORGANISATION_NAME: ${{ secrets.INFLUX_ORGANISATION_NAME }}
jobs:
  default-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: bundle install
      - run: ruby production_lead_time.rb
